config/routes.rb
Rails.application.routes.draw do
  get 'appointments/new'
  root 'static_pages#home'
  devise_for :users,controllers: { registrations: 'users/registrations' }
  
  
  resources :users, except: [:destroy,:new]
  resources :appointments
  get '/doctors', to:'users#show_doctors'
  get '/show_appointments', to:'users#show_appointments'
  get '/appointment_status', to:'users#status_mail'
  post '/add_note', to:'users#add_note'
  
 
    
  #get '/logout',to:'users/sessions#delete'

  
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord

  has_many :patient_appointments, class_name: "Appointment",
                                  foreign_key: "patient_id",
                                  dependent: :destroy
 

  has_many :doctor_appointments, class_name: "Appointment",
                                          foreign_key: "doctor_id",
                                          dependent: :destroy
  
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  
  validates :name, presence: true, length: { maximum: 50 }
  validates :mobile_number, presence: true, length: { is: 10 }
  validates :address, presence: true, length: { in: 6..300 }
  validates :role, presence: true

  def show_appointment
    #doctor_ids = "SELECT doctor_id FROM appointments
                        #WHERE patient_id = :patient_id}"
    #Appointment.where(patient_id:1)
                        
  end

  
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end
  def index
    @users = User.all.paginate(page: params[:page])
  end

  # POST /resource
   def create
     super
   end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  protected

   # you have extra params to permit, append them to the sanitizer.
  def configure_sign_up_params
     devise_parameter_sanitizer.permit(:sign_up, keys: [:role,:mobile_number,:name,:address])
   end
   private
    def after_sign_up_path_for(resource)
      
      root_url
    end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
     super
   end
 

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
    before_action :authenticate_user!, except: [:index]
    before_action :user_patient, only: [:show_doctors]
    before_action :correct_user, except: [:index]
    before_action :user_doctor, only: [:add_note,:status_mail]
    

    attr_accessor :user
    
    def index
        @users = User.all
    end

    def show
        @user=User.find(params[:id])
    end

    def destroy
         
    end
    def show_doctors
        @doctors = User.where(role: "Doctor")

    end

    def show_appointments
        if current_user.role=="Patient"
            @doctors_appointment=current_user.patient_appointments.where('time_slot >= ? AND (status ="Confirm" OR status IS NULL)',Date.today)
        else
            @patients_appointment=current_user.doctor_appointments.where('time_slot >= ? AND (status ="Confirm" OR status IS NULL)',Date.today)
        end
    end

    def user_patient
        if current_user.role!="Patient" && !current_user?(current_user)
            flash[:info]="Sorry You are not allowed"
            redirect_to user_path(current_user)
        end
    end

    def user_doctor
        if current_user.role!="Doctor" && !current_user?(current_user)
            flash[:info]="Sorry You are not allowed"
            redirect_to user_path(current_user)
        end
    end
    def correct_user
        if !current_user?(current_user)
            flash[:info]="Sorry You are not allowed"
            redirect_to user_path(current_user)
        end
    end
    
    def current_user?(user)
        user && user == current_user
    end

    def status_mail
        DoctorMailer.appointment_status(params[:email],params[:status],params[:doctor],params[:time]).deliver_now
        appointment=Appointment.find_by(doctor_id: params[:doctor_id],time_slot: params[:time])
        appointment.update_attribute(:status,params[:status])
        
        flash[:info] = "Successfully Sent email to patient and its status."
        redirect_to root_url
        
    end
    def add_note
        
        DoctorMailer.consultation_details(params[:email],params[:doctor],params[:time],params[:add_note]).deliver_now
        flash[:info] = "Successfully Sent  your note."
        redirect_to root_url


    end

end

app/helpers/users_helper.rb
module UsersHelper

    # Returns true if the given user is the current user.
    def current_user?(user)
        user && user == current_user
    end


end

app/views/users/index.html.erb
<% provide(:title, 'All users') %>
<h1>All users</h1>


<ul class="users">
<% @users.each do |user| %>
<li>

<%= link_to user.name, user_path(id:user.id) %>

<% if current_user.admin? && !current_user?(user) %>
| <%= link_to "delete", delete_user_path(id:user.id)%>

<% end %>
</li>
<% end %>
</ul>

app/views/users/show.html.erb
<h1><%= @user.name %></h1><br>
<h3><%= @user.mobile_number%></h3><br>
<h3><%= @user.address%></h3><br>
<h3><%= @user.email%></h3><br>
<h3><%= @user.role%></h3><br>


<% if current_user.role=="Patient" && !current_user?(@user)%>
<%= link_to "Book Appointment",new_appointment_path(id:@user.id)%>
<% end %>

app/views/users/show_appointments.html.erb
<ol>
<% if current_user.role=="Patient" && current_user?(current_user)%>

<% @doctors_appointment.each do |appointment| %>
<li>
<b>Reason/Disease:</b><%= appointment.reason%><br>
<b>Date:</b><%= appointment.time_slot%><br>
<b>Doctor Name:</b>

<%= appointment.doctor.name%><br>
<b>Doctor Mobile No.:</b><%= appointment.doctor.mobile_number%><br>
<b>Doctor Email:</b><%= appointment.doctor.email%><br>
<b>Address:</b>
<%= appointment.doctor.address%><br><br><br>





</li>
<%end%>
<% elsif current_user.role=="Doctor" && current_user?(current_user) %>
<% @patients_appointment.each do |appointment| %>
<li>
<b>Reason/Disease:</b><%= appointment.reason%><br>
<b>Date:</b><%= appointment.time_slot%><br>
<b>Patient Name:</b><%= appointment.patient.name%><br>

<b>Patient Mobile No.:</b><%= appointment.patient.mobile_number%><br>
<b>Patient Email:</b><%= appointment.patient.email%><br>
<b>Address:</b><%= appointment.patient.address%>
</li>
<% if appointment.status=="Confirm"%>
<h4>Add Consultation Details(Optional):</h4>
<%= form_tag "add_note", :id=>"my_form", :remote=>true do%>
<%= text_area_tag "add_note"%><br>
<div><%= hidden_field_tag :email,appointment.patient.email %></div>
<div><%= hidden_field_tag :doctor,appointment.doctor.name %></div>
<div><%= hidden_field_tag :time,appointment.time_slot %></div>
<%= button_to "Send Note", add_note_path,method: :get,class: "btn btn-primary" %>
<% end%>

<% else%>
<%= link_to "Confirm", appointment_status_path(email: appointment.patient.email,status: "Confirm",doctor:appointment.doctor.name,time:appointment.time_slot,doctor_id:appointment.doctor.id)%>
<%= link_to "Reject", appointment_status_path(email: appointment.patient.email,status: "Reject",doctor:appointment.doctor.name,time:appointment.time_slot,doctor_id:appointment.doctor.id)%>
<% end %>
<br><br><br>
<%end %>



<%end %>
</ol>
 

app/views/users/show_doctors.html.erb
<% provide(:title,"Doctors") %>

<h1>Kindly book appointment only if you are sick.</h1>
<ul class="users">
<% @doctors.each do |doctor| %>
<li>

<%= link_to doctor.name, user_path(id:doctor.id) %>

<% if current_user.admin? && !current_user?(doctor) %>
| <%= link_to "delete", delete_user_path(id:doctor.id)%>

<% end %>
</li>
<% end %>
</ul>